# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Runs the omarchy reset waybar because I can't
# debug why there are 2 are startup
exec = ~/.local/share/omarchy/bin/omarchy-restart-waybar.sh

exec-once = sunshine
