-- Generated by HyprMod

-- Settings
hl.config({
    ecosystem = {
        no_donation_nag = false,
    },
    misc = {
        force_default_wallpaper = 0,
    },
})

-- Monitors
hl.monitor({
    output = "DP-3",
    mode = "2560x1440@180.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})

-- Keybinds
hl.bind("SUPER + SHIFT + H", hl.dsp.window.move({ direction = "left" }))
hl.bind("SUPER + SHIFT + J", hl.dsp.window.move({ direction = "down" }))
hl.bind("SUPER + SHIFT + K", hl.dsp.window.move({ direction = "up" }))
hl.bind("SUPER + SHIFT + L", hl.dsp.window.move({ direction = "right" }))
